Repository HelloWorld-AICC/HelloWorld-Server, pull requests merged in 2024-08, with the labels that each got.

#36 Ci/#34
  .github/workflows/dev_deploy.yml
  elasticbeanstalk/docker-compose.yml
  src/main/java/com/example/helloworldmvc/web/controller/RootController.java
Labels: :tada: CI/CD

#38 ci : ci/cd 환경 구축
  .platform/nginx/conf.d/client_max_body_size.conf 
  build.gradle
  elasticbeanstalk/docker-compose.yml
Labels: :tada: CI/CD

#40 센터 조회 수정 api
  .platform/nginx/conf.d/client_max_body_size.conf 
  src/main/java/com/example/helloworldmvc/converter/CenterConverter.java
  src/main/java/com/example/helloworldmvc/domain/Center.java
  src/main/java/com/example/helloworldmvc/repository/CenterRepository.java
  src/main/java/com/example/helloworldmvc/service/CenterService.java
  src/main/java/com/example/helloworldmvc/service/CenterServiceImpl.java
  src/main/java/com/example/helloworldmvc/web/controller/CenterController.java
  src/main/java/com/example/helloworldmvc/web/dto/CenterResponseDTO.java
Labels: :recycle: Refactoring

#46 ci : ci/cd 환경 구축
  .github/workflows/dev_deploy.yml
Labels: :tada: CI/CD

#47 ci : ci/cd 환경 구축
  .github/workflows/dev_deploy.yml
Labels: :tada: CI/CD

#48 ci : ci/cd 환경 구축
  .github/workflows/dev_deploy.yml
Labels: :tada: CI/CD

#49 ci : ci/cd 환경 구축
  src/main/java/com/example/helloworldmvc/web/controller/RootController.java
Labels: :tada: CI/CD

#50 ci : ci/cd 환경 구축
  .github/workflows/dev_deploy.yml
  .platform/nginx/nginx.conf
  appspec.yml
  scripts/configure_nginx.sh
Labels: :tada: CI/CD

#51 ci : ci/cd 환경 구축
  .github/workflows/dev_deploy.yml
  appspec.yml
  scripts/configure_nginx.sh
Labels: :tada: CI/CD

#52 ci : ci/cd 환경 구축
  .platform/nginx/nginx.conf
Labels: :tada: CI/CD

#53 ci : ci/cd 환경 구축
  src/main/java/com/example/helloworldmvc/web/controller/RootController.java
Labels: :tada: CI/CD

#54 ci : ci/cd 환경 구축
  src/main/resources/application.yml
Labels: :tada: CI/CD

#55 ci : ci/cd 환경 구축
  src/main/resources/application.yml
Labels: :tada: CI/CD

#57 ci : ci/cd 환경 구축
  src/main/resources/application.yml
Labels: :tada: CI/CD

#59 cicd-ECS
  Dockerfile
  buildspec.yaml
  src/main/resources/application.yml
  src/test/java/com/example/helloworldmvc/HelloworldMvcApplicationTests.java
Labels: :tada: CI/CD

#61 [ci/#60] appspec.yml 위치 변경
  .github/workflows/dev_deploy.yml
  appspec.yml
  buildspec.yaml
Labels: :recycle: Refactoring, :tada: CI/CD

#62 ci : S3 -> docker로 방식 변경
  .github/workflows/dev_deploy.yml
Labels: :recycle: Refactoring, :tada: CI/CD

#63 [ci/#60] /home/ubuntu 경로에 배포
  .github/workflows/dev_deploy.yml
Labels: :recycle: Refactoring, :tada: CI/CD

#65 [Ci/#60] gradle 설정
  .github/workflows/dev_deploy.yml
Labels: :recycle: Refactoring, :tada: CI/CD

#67 [refactor/#66] redirect url 배포 서버로 설정
  src/main/java/com/example/helloworldmvc/service/GoogleServiceImpl.java
Labels: :recycle: Refactoring
